baseURL = "http://dcubed.com.au/"
languageCode = "en-us"
title = "DCUBED | Dream. Design. Develop | Brisbane Web Design"
intro = ""
theme = "DCUBED"
publishDir = "docs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"
googleAnalytics = "UA-110929649-1"
enableEmoji = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
