baseURL = "http://dcubed.com.au/"
languageCode = "en-us"
title = "Best App Developers in Brisbane | DCUBED - Dream Design Develop"
intro = ""
theme = "DCUBED"
publishDir = "docs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
